# Generated by Django 4.0.3 on 2022-04-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('parentezco', models.CharField(max_length=50)),
                ('cumple', models.DateField()),
            ],
        ),
    ]
